spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:8888/dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
